apiVersion: llmwarden.io/v1alpha1
kind: LLMAccess
metadata:
  name: agent-openai
  namespace: kagent
spec:
  providerRef:
    name: openai-production
  models:
    - "gpt-4o"
  secretName: kagent-openai
  workloadSelector:
    matchLabels:
      kagent.dev/agent: example-agent
  injection:
    env:
      - name: OPENAI_API_KEY
        secretKey: apiKey