apiVersion: v1
kind: ConfigMap
metadata:
  name: chatbot-script
  namespace: chatbot-dev
data:
  chat.py: |
    #!/usr/bin/env python3
    import os
    import json
    from http.server import HTTPServer, BaseHTTPRequestHandler

    API_KEY = os.getenv('OPENAI_API_KEY', 'not-set')

    class ChatHandler(BaseHTTPRequestHandler):
        def do_GET(self):
            if self.path == '/health':
                self.send_response(200)
                self.send_header('Content-type', 'application/json')
                self.end_headers()
                response = {
                    'status': 'healthy',
                    'api_key_configured': API_KEY != 'not-set',
                    'api_key_prefix': API_KEY[:10] if API_KEY != 'not-set' else 'none'
                }
                self.wfile.write(json.dumps(response).encode())
            elif self.path == '/':
                self.send_response(200)
                self.send_header('Content-type', 'text/html')
                self.end_headers()
                html = f"""
                <html>
                <head><title>AI Chatbot</title></head>
                <body>
                    <h1>AI Chatbot Demo</h1>
                    <p>Status: {'✅ Configured' if API_KEY != 'not-set' else '❌ Not Configured'}</p>
                    <p>API Key: {API_KEY[:15]}... (injected by llmwarden)</p>
                    <p>Model: gpt-4o-mini</p>
                    <hr>
                    <p>This is a demo app showing credential injection.</p>
                    <p>Check <a href="/health">/health</a> for JSON status.</p>
                </body>
                </html>
                """
                self.wfile.write(html.encode())
            else:
                self.send_response(404)
                self.end_headers()

    if __name__ == '__main__':
        port = 8080
        print(f'Starting chatbot server on port {port}...')
        print(f'API Key configured: {API_KEY != "not-set"}')
        server = HTTPServer(('0.0.0.0', port), ChatHandler)
        server.serve_forever()
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-chatbot
  namespace: chatbot-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-chatbot
  template:
    metadata:
      labels:
        app: ai-chatbot
    spec:
      containers:
      - name: chatbot
        image: python:3.11-slim
        command: ["python3", "/app/chat.py"]
        ports:
        - containerPort: 8080
          name: http
        volumeMounts:
        - name: script
          mountPath: /app
        # Note: OPENAI_API_KEY will be injected by llmwarden webhook
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: script
        configMap:
          name: chatbot-script
          defaultMode: 0755
---
apiVersion: v1
kind: Service
metadata:
  name: ai-chatbot
  namespace: chatbot-dev
spec:
  type: NodePort
  selector:
    app: ai-chatbot
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
    protocol: TCP
